generator:
  class: sfDoctrineGenerator
  param:
    model_class:           BirdTaxonomy
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          bird_taxonomy
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [=Bird,Taxonomytype,Taxonomy]
      filter: 
        display: [bird_id,taxonomytype_id,taxonomy_id]
      form:    ~
      edit:    ~
      new:     ~ 
