<?php

/**
 * BaseBirdTaxonomy
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $bird_id
 * @property integer $taxonomy_id
 * @property Bird $Bird
 * @property Taxonomy $Taxonomy
 * 
 * @method integer      getId()          Returns the current record's "id" value
 * @method integer      getBirdId()      Returns the current record's "bird_id" value
 * @method integer      getTaxonomyId()  Returns the current record's "taxonomy_id" value
 * @method Bird         getBird()        Returns the current record's "Bird" value
 * @method Taxonomy     getTaxonomy()    Returns the current record's "Taxonomy" value
 * @method BirdTaxonomy setId()          Sets the current record's "id" value
 * @method BirdTaxonomy setBirdId()      Sets the current record's "bird_id" value
 * @method BirdTaxonomy setTaxonomyId()  Sets the current record's "taxonomy_id" value
 * @method BirdTaxonomy setBird()        Sets the current record's "Bird" value
 * @method BirdTaxonomy setTaxonomy()    Sets the current record's "Taxonomy" value
 * 
 * @package    projectname
 * @subpackage model
 * @author     Joseph Persie
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBirdTaxonomy extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('bird_taxonomy');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('bird_id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 8,
             ));
        $this->hasColumn('taxonomy_id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Bird', array(
             'local' => 'bird_id',
             'foreign' => 'id'));

        $this->hasOne('Taxonomy', array(
             'local' => 'taxonomy_id',
             'foreign' => 'id'));
    }
}