<?php

/**
 * BaseSource
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $link
 * @property Doctrine_Collection $BirdSource
 * @property Doctrine_Collection $TaxonomytypeSource
 * @property Doctrine_Collection $TaxonomySource
 * 
 * @method integer             getId()                 Returns the current record's "id" value
 * @method string              getName()               Returns the current record's "name" value
 * @method string              getLink()               Returns the current record's "link" value
 * @method Doctrine_Collection getBirdSource()         Returns the current record's "BirdSource" collection
 * @method Doctrine_Collection getTaxonomytypeSource() Returns the current record's "TaxonomytypeSource" collection
 * @method Doctrine_Collection getTaxonomySource()     Returns the current record's "TaxonomySource" collection
 * @method Source              setId()                 Sets the current record's "id" value
 * @method Source              setName()               Sets the current record's "name" value
 * @method Source              setLink()               Sets the current record's "link" value
 * @method Source              setBirdSource()         Sets the current record's "BirdSource" collection
 * @method Source              setTaxonomytypeSource() Sets the current record's "TaxonomytypeSource" collection
 * @method Source              setTaxonomySource()     Sets the current record's "TaxonomySource" collection
 * 
 * @package    projectname
 * @subpackage model
 * @author     Joseph Persie
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSource extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('source');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 72, array(
             'type' => 'string',
             'length' => 72,
             ));
        $this->hasColumn('link', 'string', 256, array(
             'type' => 'string',
             'length' => 256,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('BirdSource', array(
             'local' => 'id',
             'foreign' => 'source_id'));

        $this->hasMany('TaxonomytypeSource', array(
             'local' => 'id',
             'foreign' => 'source_id'));

        $this->hasMany('TaxonomySource', array(
             'local' => 'id',
             'foreign' => 'source_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}