<?php

/**
 * BaseTaxonomytypeSource
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $taxonomytype_id
 * @property integer $source_id
 * @property Taxonomytype $Taxonomytype
 * @property Source $Source
 * 
 * @method integer            getId()              Returns the current record's "id" value
 * @method integer            getTaxonomytypeId()  Returns the current record's "taxonomytype_id" value
 * @method integer            getSourceId()        Returns the current record's "source_id" value
 * @method Taxonomytype       getTaxonomytype()    Returns the current record's "Taxonomytype" value
 * @method Source             getSource()          Returns the current record's "Source" value
 * @method TaxonomytypeSource setId()              Sets the current record's "id" value
 * @method TaxonomytypeSource setTaxonomytypeId()  Sets the current record's "taxonomytype_id" value
 * @method TaxonomytypeSource setSourceId()        Sets the current record's "source_id" value
 * @method TaxonomytypeSource setTaxonomytype()    Sets the current record's "Taxonomytype" value
 * @method TaxonomytypeSource setSource()          Sets the current record's "Source" value
 * 
 * @package    projectname
 * @subpackage model
 * @author     Joseph Persie
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTaxonomytypeSource extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('taxonomytype_source');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('taxonomytype_id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 8,
             ));
        $this->hasColumn('source_id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Taxonomytype', array(
             'local' => 'taxonomytype_id',
             'foreign' => 'id'));

        $this->hasOne('Source', array(
             'local' => 'source_id',
             'foreign' => 'id'));
    }
}