<?php

/**
 * BaseBird
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $propername
 * @property string $imageurl
 * @property text $wikipedia
 * @property text $about
 * @property boolean $paraphrased
 * @property text $drupalinfo
 * @property Doctrine_Collection $BirdSource
 * @property Doctrine_Collection $BirdTaxonomy
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method string              getName()         Returns the current record's "name" value
 * @method string              getPropername()   Returns the current record's "propername" value
 * @method string              getImageurl()     Returns the current record's "imageurl" value
 * @method text                getWikipedia()    Returns the current record's "wikipedia" value
 * @method text                getAbout()        Returns the current record's "about" value
 * @method boolean             getParaphrased()  Returns the current record's "paraphrased" value
 * @method text                getDrupalinfo()   Returns the current record's "drupalinfo" value
 * @method Doctrine_Collection getBirdSource()   Returns the current record's "BirdSource" collection
 * @method Doctrine_Collection getBirdTaxonomy() Returns the current record's "BirdTaxonomy" collection
 * @method Bird                setId()           Sets the current record's "id" value
 * @method Bird                setName()         Sets the current record's "name" value
 * @method Bird                setPropername()   Sets the current record's "propername" value
 * @method Bird                setImageurl()     Sets the current record's "imageurl" value
 * @method Bird                setWikipedia()    Sets the current record's "wikipedia" value
 * @method Bird                setAbout()        Sets the current record's "about" value
 * @method Bird                setParaphrased()  Sets the current record's "paraphrased" value
 * @method Bird                setDrupalinfo()   Sets the current record's "drupalinfo" value
 * @method Bird                setBirdSource()   Sets the current record's "BirdSource" collection
 * @method Bird                setBirdTaxonomy() Sets the current record's "BirdTaxonomy" collection
 * 
 * @package    projectname
 * @subpackage model
 * @author     Joseph Persie
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBird extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('bird');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 72, array(
             'type' => 'string',
             'length' => 72,
             ));
        $this->hasColumn('propername', 'string', 72, array(
             'type' => 'string',
             'length' => 72,
             ));
        $this->hasColumn('imageurl', 'string', 256, array(
             'type' => 'string',
             'length' => 256,
             ));
        $this->hasColumn('wikipedia', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('about', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('paraphrased', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
        $this->hasColumn('drupalinfo', 'text', null, array(
             'type' => 'text',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('BirdSource', array(
             'local' => 'id',
             'foreign' => 'bird_id'));

        $this->hasMany('BirdTaxonomy', array(
             'local' => 'id',
             'foreign' => 'bird_id'));
    }
}