<?php

/**
 * BaseTaxonomy
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $taxonomytype_id
 * @property string $name
 * @property string $imageurl
 * @property text $about
 * @property text $drupalinfo
 * @property boolean $described
 * @property Taxonomytype $Taxonomytype
 * @property Doctrine_Collection $BirdTaxonomy
 * @property Doctrine_Collection $TaxonomySource
 * 
 * @method integer             getId()              Returns the current record's "id" value
 * @method integer             getTaxonomytypeId()  Returns the current record's "taxonomytype_id" value
 * @method string              getName()            Returns the current record's "name" value
 * @method string              getImageurl()        Returns the current record's "imageurl" value
 * @method text                getAbout()           Returns the current record's "about" value
 * @method text                getDrupalinfo()      Returns the current record's "drupalinfo" value
 * @method boolean             getDescribed()       Returns the current record's "described" value
 * @method Taxonomytype        getTaxonomytype()    Returns the current record's "Taxonomytype" value
 * @method Doctrine_Collection getBirdTaxonomy()    Returns the current record's "BirdTaxonomy" collection
 * @method Doctrine_Collection getTaxonomySource()  Returns the current record's "TaxonomySource" collection
 * @method Taxonomy            setId()              Sets the current record's "id" value
 * @method Taxonomy            setTaxonomytypeId()  Sets the current record's "taxonomytype_id" value
 * @method Taxonomy            setName()            Sets the current record's "name" value
 * @method Taxonomy            setImageurl()        Sets the current record's "imageurl" value
 * @method Taxonomy            setAbout()           Sets the current record's "about" value
 * @method Taxonomy            setDrupalinfo()      Sets the current record's "drupalinfo" value
 * @method Taxonomy            setDescribed()       Sets the current record's "described" value
 * @method Taxonomy            setTaxonomytype()    Sets the current record's "Taxonomytype" value
 * @method Taxonomy            setBirdTaxonomy()    Sets the current record's "BirdTaxonomy" collection
 * @method Taxonomy            setTaxonomySource()  Sets the current record's "TaxonomySource" collection
 * 
 * @package    projectname
 * @subpackage model
 * @author     Joseph Persie
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTaxonomy extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('taxonomy');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('taxonomytype_id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 8,
             ));
        $this->hasColumn('name', 'string', 72, array(
             'type' => 'string',
             'length' => 72,
             ));
        $this->hasColumn('imageurl', 'string', 256, array(
             'type' => 'string',
             'length' => 256,
             ));
        $this->hasColumn('about', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('drupalinfo', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('described', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Taxonomytype', array(
             'local' => 'taxonomytype_id',
             'foreign' => 'id'));

        $this->hasMany('BirdTaxonomy', array(
             'local' => 'id',
             'foreign' => 'taxonomy_id'));

        $this->hasMany('TaxonomySource', array(
             'local' => 'id',
             'foreign' => 'taxonomy_id'));
    }
}