<?php

/**
 * BirdTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BirdTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BirdTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Bird');
    }
}