<?php

/**
 * BirdSourceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BirdSourceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BirdSourceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BirdSource');
    }
}