<?php

/**
 * BirdTaxonomy
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    projectname
 * @subpackage model
 * @author     Joseph Persie
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class BirdTaxonomy extends BaseBirdTaxonomy
{

    public function getTaxonomytype() {

        return Doctrine_Query::create()
            ->select('tt.*')
            ->from('Taxonomytype tt, tt.Taxonomy t')
            ->where('t.id = ' . $this->taxonomy_id)
             ->limit(1)
            ->fetchOne();
    }

}
