<?php

/**
 * BirdTaxonomyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BirdTaxonomyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BirdTaxonomyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BirdTaxonomy');
    }
}