<?php

/**
 * TaxonomytypeSourceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TaxonomytypeSourceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TaxonomytypeSourceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TaxonomytypeSource');
    }
}