<?php

/**
 * TaxonomyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TaxonomyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TaxonomyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Taxonomy');
    }
}