<?php

/**
 * TaxonomytypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TaxonomytypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TaxonomytypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Taxonomytype');
    }
}