<?php

/**
 * TaxonomySourceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TaxonomySourceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TaxonomySourceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TaxonomySource');
    }
}